baseurl = "/"
languageCode = "en-us"
title = "Homepage"



# [permalinks]
#   post = "/culo"


  aliases = [
      "/post/my-original-url/",
      "/post/single.html"
  ]


# [page]
#   page = "/culo"
